import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useState, useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // Runs everytime the state changes

  // const [ance, setAnce] = useState([])
  // const[stringThing, setStringThing] = useState([1,2,3,4,5,6])

  const[anceObj, updateanceObj] = useState([])
  const numAnceTotal = "3"
  const[index, updateIndex] = useState(1)

  useEffect(() => {
    // Any code here will only run once (on page load)
    // because of array that is passed through
    // runs everytime the array changes

    
    
    const myRequest = new Request("http://127.0.1:8000/ance/batch/" + numAnceTotal + "/" + index);

    fetch(myRequest, {method:"GET", headers:{Accept:"application/json"}})

      .then((response) => {
        if (!response.ok) {
          throw new Error(`HTTP error! Status: ${response.status}`);
        }

        return response.json();
      })

      .then((response) => {
        /*
        let responseLen = Object.keys(response).length;
        for (let i = 0; i < responseLen - 1; i++) {
          
          const anceDict = JSON.parse(response[i+numAnceTotal*index])
          anceObj.push(anceDict)
        */
        updateanceObj(response)
        // console.log(anceObj)

        
        //console.log(response[batch*num])
        // let responseNew = response[numAnceTotal*index].replace("\\", "");
        // setAnce(responseNew)
        //console.log(responseNew)
      });

   /*
   const myRequest = new Request("http:127.0.1:8000/ance/batch/3/0")

   fetch(myRequest, {method:"GET", headers:{Accept:"application/json"}})

      .then((response) => {
        if (!response.ok) {
          throw new Error(`HTTP error! Status: ${response.status}`);
        }

        return response.json()
      })


      .then((response) => {
        setAnce(response)
      })
      */
  }, [])

  // Create a new state
  // number is the value of the state (variable)
  // setNumber is a function? that changes the state
  // const [infoType, setInfoType] = useState(0); // Basically just updating the page
  const anceCards = []

  // for (let i = 0; i < Object.keys(anceObj).length; i++)
  const anceList = []
  for (const key in anceObj) {
    const value = anceObj[key]
    anceList.push(value)
  }

  for (const value in anceList) {
    if (typeof value !== 'boolean') {
        const valueDict = JSON.parse(value)
        // If I want to add styles to the div:
        // style = {{background: "white"}
        anceCards.push(<div>a</div>)
        console.log("valueDict")
        console.log(typeof(value))
        console.log(valueDict)
    }    
  }


  /*
  const newList = []

  console.log(anceObj.length)
  newList.push(<div style = {{background: "white"}}>{JSON.stringify("a")}</div>)
  for (const [key, value] of anceObj) {
    newList.push(<div style = {{background: "white"}}>{JSON.stringify(value[0])}</div>)
    console.log(value)
  }


  for (let i = 0; i < anceObj.length; i++) {
    return (<div style = {{background: "white"}}>{anceObj[i]}</div>)
    console.log("a")
    console.log(i)
  }
  */

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>Original JSON: Hi{/* JSON.stringify(ance) */}</p>

        <h1>Data{anceObj}</h1>
        <div id = "main">stuff</div>
        {/* setNumber changes number and updates page upon change */}
        <button onClick={() => updateIndex(index + numAnceTotal)}>Change type</button>
      </main>
    </>
  )


}

